name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable-terraform-deploy.yaml@main
    with:
      working_directory: 'specific/terraform/directory'
    secrets: inherit

